import type { Metadata } from "next";
import type { DemoVideo } from "../content/demo";
import type { ExplainerVideo } from "../content/media";
import { contact, site } from "../content/site";

/**
 * Only the Production deployment should be indexed. Vercel sets VERCEL_ENV to
 * "production", "preview" or "development"; a local `next build` has no
 * VERCEL_ENV and is treated as production so its output matches the live site.
 */
export const isIndexable = process.env.VERCEL_ENV
  ? process.env.VERCEL_ENV === "production"
  : true;

export const absoluteUrl = (path: string) =>
  path.startsWith("http") ? path : `${site.url}${path}`;

const shareImageAlt = `${site.name}: ${site.category}`;

/**
 * Metadata for one page: title, description, a self-referencing canonical and
 * matching Open Graph / Twitter fields, including the share image generated by
 * app/opengraph-image.tsx and app/twitter-image.tsx.
 *
 * Every page must call this. Next.js does not merge nested `openGraph`
 * objects: a page that sets its own `openGraph` loses the root share image
 * unless it lists it again, and a canonical set in the layout would point
 * every page at "/".
 */
export function pageMetadata({
  title,
  description,
  path,
  absoluteTitle = false,
}: {
  title: string;
  description: string;
  path: string;
  /** Use the title as-is instead of appending " — Nexaio". */
  absoluteTitle?: boolean;
}): Metadata {
  const fullTitle = absoluteTitle ? title : `${title} — ${site.name}`;
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: site.name,
      locale: site.locale,
      url: path,
      title: fullTitle,
      description,
      images: [{ url: "/opengraph-image", width: 1200, height: 630, alt: shareImageAlt, type: "image/png" }],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [{ url: "/twitter-image", width: 1200, height: 630, alt: shareImageAlt }],
    },
  };
}

const organizationId = `${site.url}/#organization`;

/**
 * Organization + WebSite structured data for the homepage. Only verified,
 * official facts: no address, no social profiles, no ratings or reviews, and
 * the phone number only once its routing is verified (content/site.ts).
 */
export function homeJsonLd() {
  const organization: Record<string, unknown> = {
    "@type": "Organization",
    "@id": organizationId,
    name: site.name,
    url: site.url,
    logo: absoluteUrl(site.logoPath),
    description: site.description,
    email: contact.email,
  };
  if (contact.phone.routingVerified) {
    organization.telephone = contact.phone.e164;
  }
  return {
    "@context": "https://schema.org",
    "@graph": [
      organization,
      {
        "@type": "WebSite",
        "@id": `${site.url}/#website`,
        name: site.name,
        url: site.url,
        inLanguage: site.language,
        publisher: { "@id": organizationId },
      },
    ],
  };
}

/**
 * BreadcrumbList for a nested page, starting at the homepage. Every item must
 * be a real, indexable page; `/industries` has no page of its own, so the
 * roofing trail is Home → Roofing.
 */
export function breadcrumbJsonLd(items: { name: string; path: string }[]) {
  const trail = [{ name: site.name, path: "/" }, ...items];
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: trail.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: item.path === "/" ? site.url : absoluteUrl(item.path),
    })),
  };
}

/**
 * VideoObject for the demo page, or null while no approved video exists.
 * Never emit this for a placeholder.
 */
export function demoVideoJsonLd(video: DemoVideo | null) {
  if (!video) return null;
  return {
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: video.title,
    description: video.description,
    thumbnailUrl: [absoluteUrl(video.poster)],
    uploadDate: video.uploadDate,
    duration: video.duration,
    contentUrl: absoluteUrl(video.src),
    inLanguage: site.language,
    publisher: {
      "@type": "Organization",
      name: site.name,
      url: site.url,
      logo: { "@type": "ImageObject", url: absoluteUrl(site.logoPath) },
    },
  };
}

/**
 * VideoObject for the explainer film. Called only by components/ExplainerVideo
 * after `explainerReady` has passed, so it never describes a placeholder.
 */
export function explainerVideoJsonLd(video: ExplainerVideo) {
  return {
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: video.title,
    description: video.description,
    thumbnailUrl: [absoluteUrl(video.poster)],
    uploadDate: video.uploadDate,
    duration: video.duration,
    contentUrl: absoluteUrl(video.src),
    inLanguage: site.language,
    publisher: {
      "@type": "Organization",
      name: site.name,
      url: site.url,
      logo: { "@type": "ImageObject", url: absoluteUrl(site.logoPath) },
    },
  };
}
